2018-01-11 08:57:06,558 ERROR 8200 nodejs.ClusterClientNoResponseError: client no response in 720672ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\examples\passport\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 8200
hostname: USER-GALVAKJA59

2018-01-11 08:58:31,744 ERROR 9280 [-/::1/-/8ms GET /test] nodejs.TypeError: Cannot read property 'isAuthenticated' of undefined
    at Object.app.router.get (E:\JS\examples\passport\app\router.js:37:27)
    at Object.<anonymous> (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.dispatch (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (E:\JS\examples\passport\node_modules\co\index.js:65:19)
    at E:\JS\examples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\examples\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\examples\passport\node_modules\co\index.js:118:63)

pid: 9280
hostname: USER-GALVAKJA59

2018-01-11 08:59:17,479 ERROR 5556 [-/::1/-/16ms GET /test] nodejs.TypeError: ctx.isAuthenticated is not a function
    at Object.app.router.use (E:\JS\examples\passport\app\router.js:50:12)
    at Object.<anonymous> (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.dispatch (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (E:\JS\examples\passport\node_modules\co\index.js:65:19)
    at E:\JS\examples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\examples\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\examples\passport\node_modules\co\index.js:118:63)

pid: 5556
hostname: USER-GALVAKJA59

2018-01-11 08:59:17,545 ERROR 5556 nodejs.TypeError: Cannot read property 'isAuthenticated' of undefined
    at Object.app.router.get (E:\JS\examples\passport\app\router.js:37:27)
    at Object.<anonymous> (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at onFulfilled (E:\JS\examples\passport\node_modules\co\index.js:65:19)
    at E:\JS\examples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (E:\JS\examples\passport\node_modules\co\index.js:50:10)
    at Object.<anonymous> (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:700:27)
    at Generator.next (<anonymous>)
    at Object.dispatch (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:334:5)

pid: 5556
hostname: USER-GALVAKJA59

2018-01-11 09:01:53,834 ERROR 4368 [-/::1/-/19ms GET /home] nodejs.TypeError: ctx.isAuthenticated is not a function
    at Object.app.router.use (E:\JS\examples\passport\app\router.js:51:12)
    at Object.<anonymous> (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.dispatch (E:\JS\examples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (E:\JS\examples\passport\node_modules\co\index.js:65:19)
    at E:\JS\examples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\examples\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\examples\passport\node_modules\co\index.js:118:63)

pid: 4368
hostname: USER-GALVAKJA59

2018-01-11 10:05:53,536 ERROR 8200 nodejs.ClusterClientNoResponseError: client no response in 86366ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\examples\passport\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 8200
hostname: USER-GALVAKJA59

2018-01-11 13:25:11,542 ERROR 8200 nodejs.ClusterClientNoResponseError: client no response in 1237599ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\examples\passport\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 8200
hostname: USER-GALVAKJA59

2018-01-11 14:27:12,541 ERROR 8200 nodejs.ClusterClientNoResponseError: client no response in 1580929ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\examples\passport\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 8200
hostname: USER-GALVAKJA59

2018-01-15 10:17:52,127 ERROR 7732 [-/::1/-/7ms GET /home] nodejs.TypeError: ctx.isAuthenticated is not a function
    at Object.app.router.use (E:\JS\eggExamples\passport\app\router.js:51:12)
    at Object.<anonymous> (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (E:\JS\eggExamples\passport\node_modules\co\index.js:65:19)
    at E:\JS\eggExamples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\eggExamples\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\eggExamples\passport\node_modules\co\index.js:118:63)

pid: 7732
hostname: USER-GALVAKJA59

2018-01-15 10:29:33,564 ERROR 6200 [-/::1/-/4ms GET /test] nodejs.TypeError: Cannot read property 'isAuthenticated' of undefined
    at Object.app.router.get (E:\JS\eggExamples\passport\app\router.js:29:27)
    at Object.<anonymous> (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (E:\JS\eggExamples\passport\node_modules\co\index.js:65:19)
    at E:\JS\eggExamples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\eggExamples\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\eggExamples\passport\node_modules\co\index.js:118:63)

pid: 6200
hostname: USER-GALVAKJA59

2018-01-15 10:37:38,908 ERROR 6720 [-/::1/-/4ms GET /logout] nodejs.TypeError: Cannot convert undefined or null to object
    at IncomingMessage.req.logout.req.logOut (E:\JS\eggExamples\passport\node_modules\passport-oauth\node_modules\passport\lib\passport\http\request.js:65:25)
    at Object.logout (E:\JS\eggExamples\passport\node_modules\egg-passport\app\extend\context.js:36:14)
    at UserController.logout (E:\JS\eggExamples\passport\app\controller\user.js:9:9)
    at callController (E:\JS\eggExamples\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (E:\JS\eggExamples\passport\node_modules\co\index.js:65:19)
    at E:\JS\eggExamples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\eggExamples\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\eggExamples\passport\node_modules\co\index.js:118:63)

pid: 6720
hostname: USER-GALVAKJA59

2018-01-15 11:25:24,335 ERROR 3448 [-/::1/-/8ms GET /login] nodejs.ReferenceError: safe is not defined
    at HomeController.login (E:\JS\eggExamples\passport\app\controller\home.js:11:48)
    at callController (E:\JS\eggExamples\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (E:\JS\eggExamples\passport\node_modules\co\index.js:65:19)
    at E:\JS\eggExamples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\eggExamples\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\eggExamples\passport\node_modules\co\index.js:118:63)
    at next (E:\JS\eggExamples\passport\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\eggExamples\passport\node_modules\co\index.js:69:7)

pid: 3448
hostname: USER-GALVAKJA59

2018-01-15 11:25:46,316 ERROR 6600 [-/::1/-/34ms POST /login?_csrf=z0hKfFtN-ldEX0ZzoiC_51ZJ9XPHaeDZAjdI] nodejs.ReferenceError: debug is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:15:5)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)

pid: 6600
hostname: USER-GALVAKJA59

2018-01-15 11:26:18,083 ERROR 6600 [-/::1/-/4ms POST /login?_csrf=z0hKfFtN-ldEX0ZzoiC_51ZJ9XPHaeDZAjdI] nodejs.ReferenceError: debug is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:15:5)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)

pid: 6600
hostname: USER-GALVAKJA59

2018-01-15 11:26:37,801 ERROR 6600 [-/::1/-/3ms POST /login?_csrf=jnj56s6k-FmZxA05VV_cbavXayEwlFdurC_E] nodejs.ReferenceError: debug is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:15:5)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)

pid: 6600
hostname: USER-GALVAKJA59

2018-01-15 11:27:16,936 ERROR 6600 [-/::1/-/2ms POST /login?_csrf=6IUWKwl2-vR2s9u6IKiSCFBaZAA3gHaqsQMk] nodejs.ReferenceError: debug is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:15:5)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)

pid: 6600
hostname: USER-GALVAKJA59

2018-01-15 11:51:03,036 ERROR 7016 [-/::1/-/40ms POST /login?_csrf=05MIWUYF-lrvNOarPr8FQPBrdASRD4DcMbWc] nodejs.ReferenceError: ctx is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:17:5)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)

pid: 7016
hostname: USER-GALVAKJA59

2018-01-15 11:51:52,246 ERROR 7016 [-/::1/-/4ms POST /login?_csrf=05MIWUYF-lrvNOarPr8FQPBrdASRD4DcMbWc] nodejs.ReferenceError: ctx is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:17:5)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)

pid: 7016
hostname: USER-GALVAKJA59

2018-01-15 11:52:14,278 ERROR 7016 [-/::1/-/3ms POST /login?_csrf=F0nt2NVs-_Vndd1p6KVM7_gLLKIZCJ7sLHkU] nodejs.ReferenceError: ctx is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:17:5)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (E:\JS\eggExamples\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (E:\JS\eggExamples\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)

pid: 7016
hostname: USER-GALVAKJA59

2018-01-15 12:19:57,000 ERROR 5036 [-/::1/-/35ms POST /login?_csrf=GLNndwNY-KFIQ2nAmQvtoHkuDiFFVBN30Smk] nodejs.TypeError: Cannot set property 'id' of undefined
    at app.passport.verify (E:\JS\eggExamples\passport\app.js:27:18)
    at E:\JS\eggExamples\passport\node_modules\egg-passport\lib\passport.js:71:22
    at Generator.next (<anonymous>)
    at onFulfilled (E:\JS\eggExamples\passport\node_modules\co\index.js:65:19)
    at E:\JS\eggExamples\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (E:\JS\eggExamples\passport\node_modules\co\index.js:50:10)
    at EggPassport.doVerify (E:\JS\eggExamples\passport\node_modules\egg-passport\lib\passport.js:68:5)
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\eggExamples\passport\app.js:16:18)
    at Strategy.authenticate (E:\JS\eggExamples\passport\node_modules\passport-local\lib\strategy.js:88:12)

pid: 5036
hostname: USER-GALVAKJA59

2018-01-15 16:15:48,115 ERROR 6180 [-/::1/-/35ms POST /login] nodejs.TypeError: Cannot read property 'User' of undefined
    at app.passport.verify (E:\JS\passport\app.js:28:40)
    at E:\JS\passport\node_modules\egg-passport\lib\passport.js:71:22
    at Generator.next (<anonymous>)
    at onFulfilled (E:\JS\passport\node_modules\co\index.js:65:19)
    at E:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (E:\JS\passport\node_modules\co\index.js:50:10)
    at EggPassport.doVerify (E:\JS\passport\node_modules\egg-passport\lib\passport.js:68:5)
    at Strategy.app.passport.use.LocalStrategy [as _verify] (E:\JS\passport\app.js:16:18)
    at Strategy.authenticate (E:\JS\passport\node_modules\passport-local\lib\strategy.js:88:12)

pid: 6180
hostname: USER-GALVAKJA59

2018-01-16 08:37:08,525 ERROR 3356 nodejs.ClusterClientNoResponseError: client no response in 52910108ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\passport\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 3356
hostname: USER-GALVAKJA59

